defmodule Cyphi.CourseTemplate do
  @moduledoc """
  Provides struct and types for a CourseTemplate
  """

  @type t :: %__MODULE__{
          allow_reenrollment: boolean | nil,
          allow_unenrollment: boolean | nil,
          auto_complete_on_visit: boolean | nil,
          auto_enroll_from_waitlist: boolean | nil,
          course_code: String.t() | nil,
          credits: number | nil,
          custom_fields: map | nil,
          delete_history_on_unenroll: boolean | nil,
          disable_completion: boolean | nil,
          display_in_catalog: boolean | nil,
          enrollment_open: boolean | nil,
          finish_at: Date.t() | nil,
          id: integer | nil,
          locked: boolean | nil,
          long_description: String.t() | nil,
          max_seats: integer | nil,
          max_students: integer | nil,
          metadata: Cyphi.CourseTemplateMetadata.t() | nil,
          must_repurchase_to_reenroll: boolean | nil,
          name: String.t() | nil,
          open_enrollment: boolean | nil,
          organization_id: integer | nil,
          organization_name: String.t() | nil,
          path: boolean | nil,
          picture: String.t() | nil,
          price: number | nil,
          private: boolean | nil,
          section_code: String.t() | nil,
          short_description: String.t() | nil,
          sis_id: String.t() | nil,
          sis_pid: String.t() | nil,
          start_at: Date.t() | nil,
          style: String.t() | nil,
          tags: [String.t()] | nil,
          tax_exempt: boolean | nil,
          time_zone: String.t() | nil,
          waitlist_after_limit: boolean | nil,
          weight_using_categories: boolean | nil,
          weights: String.t() | nil
        }

  defstruct [
    :allow_reenrollment,
    :allow_unenrollment,
    :auto_complete_on_visit,
    :auto_enroll_from_waitlist,
    :course_code,
    :credits,
    :custom_fields,
    :delete_history_on_unenroll,
    :disable_completion,
    :display_in_catalog,
    :enrollment_open,
    :finish_at,
    :id,
    :locked,
    :long_description,
    :max_seats,
    :max_students,
    :metadata,
    :must_repurchase_to_reenroll,
    :name,
    :open_enrollment,
    :organization_id,
    :organization_name,
    :path,
    :picture,
    :price,
    :private,
    :section_code,
    :short_description,
    :sis_id,
    :sis_pid,
    :start_at,
    :style,
    :tags,
    :tax_exempt,
    :time_zone,
    :waitlist_after_limit,
    :weight_using_categories,
    :weights
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      allow_reenrollment: :boolean,
      allow_unenrollment: :boolean,
      auto_complete_on_visit: :boolean,
      auto_enroll_from_waitlist: :boolean,
      course_code: :string,
      credits: {:number, "float"},
      custom_fields: :map,
      delete_history_on_unenroll: :boolean,
      disable_completion: :boolean,
      display_in_catalog: :boolean,
      enrollment_open: :boolean,
      finish_at: {:string, "date"},
      id: :integer,
      locked: :boolean,
      long_description: :string,
      max_seats: :integer,
      max_students: :integer,
      metadata: {Cyphi.CourseTemplateMetadata, :t},
      must_repurchase_to_reenroll: :boolean,
      name: :string,
      open_enrollment: :boolean,
      organization_id: :integer,
      organization_name: :string,
      path: :boolean,
      picture: :string,
      price: {:number, "float"},
      private: :boolean,
      section_code: :string,
      short_description: :string,
      sis_id: :string,
      sis_pid: :string,
      start_at: {:string, "date"},
      style: :string,
      tags: [:string],
      tax_exempt: :boolean,
      time_zone: :string,
      waitlist_after_limit: :boolean,
      weight_using_categories: :boolean,
      weights: :string
    ]
  end
end
