defmodule Cyphi.Learner do
  @moduledoc """
  Provides struct and types for a Learner
  """

  @type t :: %__MODULE__{
          completed: boolean | nil,
          completed_at: DateTime.t() | nil,
          completed_by_id: integer | nil,
          course: map | nil,
          course_archived: boolean | nil,
          course_id: integer | nil,
          deactivated: boolean | nil,
          deactivated_at: DateTime.t() | nil,
          deactivated_by: map | nil,
          deactivated_by_id: integer | nil,
          enroll_type: String.t() | nil,
          enrolled_at: DateTime.t() | nil,
          enrolled_by: map | nil,
          enrolled_by_id: integer | nil,
          grade: String.t() | nil,
          id: integer | nil,
          last_visited_at: DateTime.t() | nil,
          order_item: map | nil,
          order_item_id: integer | nil,
          override_at: DateTime.t() | nil,
          override_by_id: integer | nil,
          override_comment: String.t() | nil,
          override_percent: number | nil,
          percent: number | nil,
          progress: map | nil,
          reactivated_at: DateTime.t() | nil,
          reactivated_by: map | nil,
          reactivated_by_id: integer | nil,
          started: boolean | nil,
          started_at: DateTime.t() | nil,
          time_spent: integer | nil,
          transferred: boolean | nil,
          transferred_at: DateTime.t() | nil,
          transferred_by: map | nil,
          transferred_by_id: integer | nil,
          transferred_from: map | nil,
          transferred_from_id: integer | nil,
          transferred_to: map | nil,
          transferred_to_id: integer | nil,
          unenrolled: boolean | nil,
          unenrolled_at: DateTime.t() | nil,
          unenrolled_by: map | nil,
          unenrolled_by_id: integer | nil,
          user: map | nil,
          user_archived: boolean | nil,
          user_id: integer
        }

  # credo:disable-for-next-line
  defstruct [
    :completed,
    :completed_at,
    :completed_by_id,
    :course,
    :course_archived,
    :course_id,
    :deactivated,
    :deactivated_at,
    :deactivated_by,
    :deactivated_by_id,
    :enroll_type,
    :enrolled_at,
    :enrolled_by,
    :enrolled_by_id,
    :grade,
    :id,
    :last_visited_at,
    :order_item,
    :order_item_id,
    :override_at,
    :override_by_id,
    :override_comment,
    :override_percent,
    :percent,
    :progress,
    :reactivated_at,
    :reactivated_by,
    :reactivated_by_id,
    :started,
    :started_at,
    :time_spent,
    :transferred,
    :transferred_at,
    :transferred_by,
    :transferred_by_id,
    :transferred_from,
    :transferred_from_id,
    :transferred_to,
    :transferred_to_id,
    :unenrolled,
    :unenrolled_at,
    :unenrolled_by,
    :unenrolled_by_id,
    :user,
    :user_archived,
    :user_id
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      completed: :boolean,
      completed_at: {:string, "date-time"},
      completed_by_id: :integer,
      course: :map,
      course_archived: :boolean,
      course_id: :integer,
      deactivated: :boolean,
      deactivated_at: {:string, "date-time"},
      deactivated_by: :map,
      deactivated_by_id: :integer,
      enroll_type: :string,
      enrolled_at: {:string, "date-time"},
      enrolled_by: :map,
      enrolled_by_id: :integer,
      grade: :string,
      id: :integer,
      last_visited_at: {:string, "date-time"},
      order_item: :map,
      order_item_id: :integer,
      override_at: {:string, "date-time"},
      override_by_id: :integer,
      override_comment: :string,
      override_percent: {:number, "float"},
      percent: {:number, "float"},
      progress: :map,
      reactivated_at: {:string, "date-time"},
      reactivated_by: :map,
      reactivated_by_id: :integer,
      started: :boolean,
      started_at: {:string, "date-time"},
      time_spent: :integer,
      transferred: :boolean,
      transferred_at: {:string, "date-time"},
      transferred_by: :map,
      transferred_by_id: :integer,
      transferred_from: :map,
      transferred_from_id: :integer,
      transferred_to: :map,
      transferred_to_id: :integer,
      unenrolled: :boolean,
      unenrolled_at: {:string, "date-time"},
      unenrolled_by: :map,
      unenrolled_by_id: :integer,
      user: :map,
      user_archived: :boolean,
      user_id: :integer
    ]
  end
end
