defmodule Cyphi.User do
  @moduledoc """
  Provides struct and types for a User
  """

  @type t :: %__MODULE__{
          about: String.t() | nil,
          added_by_id: integer | nil,
          archived: boolean | nil,
          archived_at: DateTime.t() | nil,
          archiver_id: integer | nil,
          birthdate: Date.t() | nil,
          city: String.t() | nil,
          country: String.t() | nil,
          custom_fields: map | nil,
          email: String.t() | nil,
          email_sync: String.t() | nil,
          first_login_at: DateTime.t() | nil,
          first_name: String.t() | nil,
          gender: String.t() | nil,
          id: integer | nil,
          instructorID: String.t() | nil,
          job_title_id: integer | nil,
          job_title_name: String.t() | nil,
          joined_at: DateTime.t() | nil,
          language: String.t() | nil,
          last_login_at: DateTime.t() | nil,
          last_login_ip: String.t() | nil,
          last_name: String.t() | nil,
          learnerID: String.t() | nil,
          manager_id: integer | nil,
          manager_name: String.t() | nil,
          mobile_phone: String.t() | nil,
          nick_name: String.t() | nil,
          organization_id: integer | nil,
          organization_name: String.t() | nil,
          password: String.t() | nil,
          phone: String.t() | nil,
          roles: [String.t()] | nil,
          sis_id: String.t() | nil,
          sis_pid: String.t() | nil,
          sms_email: String.t() | nil,
          sms_sync: String.t() | nil,
          state: String.t() | nil,
          street_1: String.t() | nil,
          street_2: String.t() | nil,
          street_3: String.t() | nil,
          tags: [String.t()] | nil,
          time_zone: String.t() | nil,
          userid: String.t() | nil,
          year_of_graduation: integer | nil,
          zip: String.t() | nil
        }

  # credo:disable-for-next-line
  defstruct [
    :about,
    :added_by_id,
    :archived,
    :archived_at,
    :archiver_id,
    :birthdate,
    :city,
    :country,
    :custom_fields,
    :email,
    :email_sync,
    :first_login_at,
    :first_name,
    :gender,
    :id,
    :instructorID,
    :job_title_id,
    :job_title_name,
    :joined_at,
    :language,
    :last_login_at,
    :last_login_ip,
    :last_name,
    :learnerID,
    :manager_id,
    :manager_name,
    :mobile_phone,
    :nick_name,
    :organization_id,
    :organization_name,
    :password,
    :phone,
    :roles,
    :sis_id,
    :sis_pid,
    :sms_email,
    :sms_sync,
    :state,
    :street_1,
    :street_2,
    :street_3,
    :tags,
    :time_zone,
    :userid,
    :year_of_graduation,
    :zip
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      about: :string,
      added_by_id: :integer,
      archived: :boolean,
      archived_at: {:string, "date-time"},
      archiver_id: :integer,
      birthdate: {:string, "date"},
      city: :string,
      country: :string,
      custom_fields: :map,
      email: :string,
      email_sync: :string,
      first_login_at: {:string, "date-time"},
      first_name: :string,
      gender: :string,
      id: :integer,
      instructorID: :string,
      job_title_id: :integer,
      job_title_name: :string,
      joined_at: {:string, "date-time"},
      language: :string,
      last_login_at: {:string, "date-time"},
      last_login_ip: :string,
      last_name: :string,
      learnerID: :string,
      manager_id: :integer,
      manager_name: :string,
      mobile_phone: :string,
      nick_name: :string,
      organization_id: :integer,
      organization_name: :string,
      password: :string,
      phone: :string,
      roles: [:string],
      sis_id: :string,
      sis_pid: :string,
      sms_email: :string,
      sms_sync: :string,
      state: :string,
      street_1: :string,
      street_2: :string,
      street_3: :string,
      tags: [:string],
      time_zone: :string,
      userid: :string,
      year_of_graduation: :integer,
      zip: :string
    ]
  end
end
